// تم حذف 'package:cloud_firestore/cloud_firestore.dart'

enum ReminderType {
  inspection,
  treatment,
  feeding,
  frameAddition,
  frameRemoval,
  splitting,
  nucleusUpgrade,
  queenCheck,
  diseaseCheck,
  weatherAlert,
  harvestReady,
  medicationEnd,
  custom,
}

enum ReminderPriority {
  low,
  medium,
  high,
  urgent,
}

enum ReminderStatus {
  pending,
  completed,
  dismissed,
  snoozed,
}

enum TriggerCondition {
  frameCount,
  timeInterval,
  weatherChange,
  diseaseDetected,
  treatmentDue,
  inspectionOverdue,
  nucleusGrowth,
  queenAbsent,
  custom,
}

class ReminderModel {
  final String id;
  final String userId;
  final String? hiveId;
  final ReminderType type;
  final ReminderPriority priority;
  final ReminderStatus status;
  final String title;
  final String description;
  final DateTime scheduledDate;
  final DateTime? completedDate;
  final DateTime? snoozeUntil;
  final bool isRecurring;
  final int recurringIntervalDays;
  final TriggerCondition? triggerCondition;
  final Map<String, dynamic>? triggerParameters;
  final bool isAutoGenerated;
  final String? parentReminderId;
  final List<String> tags;
  final Map<String, dynamic>? actionData;
  final String? notes;

  ReminderModel({
    required this.id,
    required this.userId,
    this.hiveId,
    required this.type,
    required this.priority,
    required this.status,
    required this.title,
    required this.description,
    required this.scheduledDate,
    this.completedDate,
    this.snoozeUntil,
    this.isRecurring = false,
    this.recurringIntervalDays = 0,
    this.triggerCondition,
    this.triggerParameters,
    this.isAutoGenerated = false,
    this.parentReminderId,
    this.tags = const [],
    this.actionData,
    this.notes,
  });

  // Getters for backward compatibility
  DateTime get reminderDate => scheduledDate;
  bool get isCompleted => status == ReminderStatus.completed;

  // تحويل النموذج إلى Map للتوافق مع Supabase
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'user_id': userId,
      'hive_id': hiveId,
      'type': type.name,
      'priority': priority.name,
      'status': status.name,
      'title': title,
      'description': description,
      'scheduled_date': scheduledDate.toIso8601String(),
      'completed_date': completedDate?.toIso8601String(),
      'snooze_until': snoozeUntil?.toIso8601String(),
      'is_recurring': isRecurring,
      'recurring_interval_days': recurringIntervalDays,
      'trigger_condition': triggerCondition?.name,
      'trigger_parameters': triggerParameters,
      'is_auto_generated': isAutoGenerated,
      'parent_reminder_id': parentReminderId,
      'tags': tags,
      'action_data': actionData,
      'notes': notes,
    };
  }

  // إنشاء نموذج من Map قادم من Supabase
  factory ReminderModel.fromMap(Map<String, dynamic> map) {
    return ReminderModel(
      id: map['id'] ?? '',
      userId: map['user_id'] ?? '',
      hiveId: map['hive_id'],
      type: ReminderType.values.firstWhere(
            (e) => e.name == map['type'],
        orElse: () => ReminderType.custom,
      ),
      priority: ReminderPriority.values.firstWhere(
            (e) => e.name == map['priority'],
        orElse: () => ReminderPriority.medium,
      ),
      status: ReminderStatus.values.firstWhere(
            (e) => e.name == map['status'],
        orElse: () => ReminderStatus.pending,
      ),
      title: map['title'] ?? '',
      description: map['description'] ?? '',
      scheduledDate: DateTime.parse(map['scheduled_date']),
      completedDate: map['completed_date'] != null
          ? DateTime.parse(map['completed_date'])
          : null,
      snoozeUntil: map['snooze_until'] != null
          ? DateTime.parse(map['snooze_until'])
          : null,
      isRecurring: map['is_recurring'] ?? false,
      recurringIntervalDays: map['recurring_interval_days'] ?? 0,
      triggerCondition: map['trigger_condition'] != null
          ? TriggerCondition.values.firstWhere(
            (e) => e.name == map['trigger_condition'],
        orElse: () => TriggerCondition.custom,
      )
          : null,
      triggerParameters: map['trigger_parameters'] != null ? Map<String, dynamic>.from(map['trigger_parameters']) : null,
      isAutoGenerated: map['is_auto_generated'] ?? false,
      parentReminderId: map['parent_reminder_id'],
      tags: List<String>.from(map['tags'] ?? []),
      actionData: map['action_data'] != null ? Map<String, dynamic>.from(map['action_data']) : null,
      notes: map['notes'],
    );
  }

  factory ReminderModel.fromSupabase(Map<String, dynamic> data) {
    return ReminderModel.fromMap(data);
  }

  ReminderModel copyWith({
    String? id,
    String? userId,
    String? hiveId,
    ReminderType? type,
    ReminderPriority? priority,
    ReminderStatus? status,
    String? title,
    String? description,
    DateTime? scheduledDate,
    DateTime? completedDate,
    DateTime? snoozeUntil,
    bool? isRecurring,
    int? recurringIntervalDays,
    TriggerCondition? triggerCondition,
    Map<String, dynamic>? triggerParameters,
    bool? isAutoGenerated,
    String? parentReminderId,
    List<String>? tags,
    Map<String, dynamic>? actionData,
    String? notes,
  }) {
    return ReminderModel(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      hiveId: hiveId ?? this.hiveId,
      type: type ?? this.type,
      priority: priority ?? this.priority,
      status: status ?? this.status,
      title: title ?? this.title,
      description: description ?? this.description,
      scheduledDate: scheduledDate ?? this.scheduledDate,
      completedDate: completedDate ?? this.completedDate,
      snoozeUntil: snoozeUntil ?? this.snoozeUntil,
      isRecurring: isRecurring ?? this.isRecurring,
      recurringIntervalDays: recurringIntervalDays ?? this.recurringIntervalDays,
      triggerCondition: triggerCondition ?? this.triggerCondition,
      triggerParameters: triggerParameters ?? this.triggerParameters,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      parentReminderId: parentReminderId ?? this.parentReminderId,
      tags: tags ?? this.tags,
      actionData: actionData ?? this.actionData,
      notes: notes ?? this.notes,
    );
  }
}

class SmartReminderTrigger {
  static ReminderModel createFrameAdditionReminder({
    required String userId,
    required String hiveId,
    required String hiveNumber,
    required int currentFrames,
    required int targetFrames,
  }) {
    return ReminderModel(
      id: DateTime.now().millisecondsSinceEpoch.toString(),
      userId: userId,
      hiveId: hiveId,
      type: ReminderType.frameAddition,
      priority: ReminderPriority.high,
      status: ReminderStatus.pending,
      title: 'إضافة إطار للخلية $hiveNumber',
      description: 'الخلية $hiveNumber تحتاج لإضافة إطار. العدد الحالي: $currentFrames إطار',
      scheduledDate: DateTime.now(),
      isAutoGenerated: true,
      triggerCondition: TriggerCondition.frameCount,
      triggerParameters: {
        'currentFrames': currentFrames,
        'targetFrames': targetFrames,
        'action': 'add',
      },
      actionData: {
        'hiveNumber': hiveNumber,
        'recommendedAction': 'add_frame',
        'urgency': 'high',
      },
      tags: ['auto-generated', 'frame-management'],
    );
  }

  static ReminderModel createSplittingReminder({
    required String userId,
    required String hiveId,
    required String hiveNumber,
    required int frameCount,
  }) {
    return ReminderModel(
      id: DateTime.now().millisecondsSinceEpoch.toString(),
      userId: userId,
      hiveId: hiveId,
      type: ReminderType.splitting,
      priority: ReminderPriority.urgent, // تم الإصلاح
      status: ReminderStatus.pending,
      title: 'تقسيم الخلية $hiveNumber',
      description: 'الخلية $hiveNumber جاهزة للتقسيم. العدد الحالي: $frameCount إطار',
      scheduledDate: DateTime.now(),
      isAutoGenerated: true,
      triggerCondition: TriggerCondition.frameCount,
      triggerParameters: {
        'frameCount': frameCount,
        'readyForSplit': true,
      },
      actionData: {
        'hiveNumber': hiveNumber,
        'recommendedAction': 'split_hive',
        'urgency': 'urgent',
        'optimalTime': 'morning',
      },
      tags: ['auto-generated', 'splitting', 'urgent'],
    );
  }

  static ReminderModel createNucleusUpgradeReminder({
    required String userId,
    required String nucleusId,
    required String nucleusNumber,
    required int frameCount,
  }) {
    return ReminderModel(
      id: DateTime.now().millisecondsSinceEpoch.toString(),
      userId: userId,
      hiveId: nucleusId,
      type: ReminderType.nucleusUpgrade,
      priority: ReminderPriority.high, // تم الإصلاح
      status: ReminderStatus.pending,
      title: 'ترقية الطرد $nucleusNumber',
      description: 'الطرد $nucleusNumber وصل لـ $frameCount إطارات وجاهز للترقية لخلية كاملة',
      scheduledDate: DateTime.now(),
      isAutoGenerated: true,
      triggerCondition: TriggerCondition.nucleusGrowth,
      triggerParameters: {
        'frameCount': frameCount,
        'readyForUpgrade': true,
      },
      actionData: {
        'nucleusNumber': nucleusNumber,
        'recommendedAction': 'upgrade_to_hive',
        'urgency': 'high',
      },
      tags: ['auto-generated', 'nucleus-upgrade'],
    );
  }

  static ReminderModel createInspectionReminder({
    required String userId,
    required String hiveId,
    required String hiveNumber,
    required DateTime lastInspection,
    required int intervalDays,
  }) {
    final nextInspection = lastInspection.add(Duration(days: intervalDays));

    return ReminderModel(
      id: DateTime.now().millisecondsSinceEpoch.toString(),
      userId: userId,
      hiveId: hiveId,
      type: ReminderType.inspection,
      priority: ReminderPriority.medium, // تم الإصلاح
      status: ReminderStatus.pending,
      title: 'فحص الخلية $hiveNumber',
      description: 'حان موعد فحص الخلية $hiveNumber. آخر فحص كان في ${_formatDate(lastInspection)}',
      scheduledDate: nextInspection,
      isRecurring: true,
      recurringIntervalDays: intervalDays,
      isAutoGenerated: true,
      triggerCondition: TriggerCondition.timeInterval,
      triggerParameters: {
        'lastInspection': lastInspection.toIso8601String(),
        'intervalDays': intervalDays,
      },
      actionData: {
        'hiveNumber': hiveNumber,
        'recommendedAction': 'inspect_hive',
      },
      tags: ['auto-generated', 'inspection', 'recurring'],
    );
  }

  static ReminderModel createTreatmentReminder({
    required String userId,
    required String hiveId,
    required String hiveNumber,
    required String treatmentName,
    required DateTime treatmentDate,
  }) {
    return ReminderModel(
      id: DateTime.now().millisecondsSinceEpoch.toString(),
      userId: userId,
      hiveId: hiveId,
      type: ReminderType.treatment,
      priority: ReminderPriority.high, // تم الإصلاح
      status: ReminderStatus.pending,
      title: 'علاج الخلية $hiveNumber',
      description: 'موعد علاج $treatmentName للخلية $hiveNumber',
      scheduledDate: treatmentDate,
      isAutoGenerated: true,
      triggerCondition: TriggerCondition.treatmentDue,
      triggerParameters: {
        'treatmentName': treatmentName,
        'treatmentDate': treatmentDate.toIso8601String(),
      },
      actionData: {
        'hiveNumber': hiveNumber,
        'treatmentName': treatmentName,
        'recommendedAction': 'apply_treatment',
      },
      tags: ['auto-generated', 'treatment'],
    );
  }

  static ReminderModel createWeatherAlert({
    required String userId,
    required String weatherCondition,
    required String alertMessage,
  }) {
    return ReminderModel(
      id: DateTime.now().millisecondsSinceEpoch.toString(),
      userId: userId,
      type: ReminderType.weatherAlert,
      priority: ReminderPriority.medium, // تم الإصلاح
      status: ReminderStatus.pending,
      title: 'تنبيه طقس',
      description: alertMessage,
      scheduledDate: DateTime.now(),
      isAutoGenerated: true,
      triggerCondition: TriggerCondition.weatherChange,
      triggerParameters: {
        'weatherCondition': weatherCondition,
        'alertTime': DateTime.now().toIso8601String(),
      },
      actionData: {
        'recommendedAction': 'check_weather_impact',
        'weatherCondition': weatherCondition,
      },
      tags: ['auto-generated', 'weather', 'alert'],
    );
  }

  static String _formatDate(DateTime date) {
    return '${date.day}/${date.month}/${date.year}';
  }
}

extension ReminderModelExtensions on ReminderModel {
  String get typeDisplayName {
    switch (type) {
      case ReminderType.inspection:
        return 'فحص';
      case ReminderType.treatment:
        return 'علاج';
      case ReminderType.feeding:
        return 'تغذية';
      case ReminderType.frameAddition:
        return 'إضافة إطار';
      case ReminderType.frameRemoval:
        return 'إزالة إطار';
      case ReminderType.splitting:
        return 'تقسيم';
      case ReminderType.nucleusUpgrade:
        return 'ترقية طرد';
      case ReminderType.queenCheck:
        return 'فحص الملكة';
      case ReminderType.diseaseCheck:
        return 'فحص الأمراض';
      case ReminderType.weatherAlert:
        return 'تنبيه طقس';
      case ReminderType.harvestReady:
        return 'جاهز للجني';
      case ReminderType.medicationEnd:
        return 'انتهاء العلاج';
      case ReminderType.custom:
        return 'مخصص';
    }
  }

  String get priorityDisplayName {
    switch (priority) {
      case ReminderPriority.low: // تم الإصلاح
        return 'منخفض';
      case ReminderPriority.medium: // تم الإصلاح
        return 'متوسط';
      case ReminderPriority.high: // تم الإصلاح
        return 'عالي';
      case ReminderPriority.urgent: // تم الإصلاح
        return 'عاجل';
    }
  }

  String get statusDisplayName {
    switch (status) {
      case ReminderStatus.pending:
        return 'معلق';
      case ReminderStatus.completed:
        return 'مكتمل';
      case ReminderStatus.dismissed:
        return 'مرفوض';
      case ReminderStatus.snoozed:
        return 'مؤجل';
    }
  }

  bool get isOverdue {
    if (status != ReminderStatus.pending) return false;
    if (snoozeUntil != null && DateTime.now().isBefore(snoozeUntil!)) return false;
    return DateTime.now().isAfter(scheduledDate);
  }

  bool get isDueToday {
    final now = DateTime.now();
    final today = DateTime(now.year, now.month, now.day);
    final scheduleDay = DateTime(scheduledDate.year, scheduledDate.month, scheduledDate.day);
    return today == scheduleDay && status == ReminderStatus.pending;
  }

  bool get isDueSoon {
    final now = DateTime.now();
    final difference = scheduledDate.difference(now).inHours;
    return difference <= 24 && difference > 0 && status == ReminderStatus.pending;
  }

  String get urgencyLevel {
    if (isOverdue) return 'متأخر';
    if (isDueToday) return 'اليوم';
    if (isDueSoon) return 'قريباً';
    return 'مجدول';
  }
}
